apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sample-component
  annotations:
    github.com/project-slug: Meeranmk/portfolio
spec:
  type: service
  owner: team-a
  lifecycle: production
